version: '3'
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    deploy:
        resources:
            limits:
                memory: 2G
    ports:
     - "8111:8111"
    volumes:
      - ~/teamcity/data:/data/teamcity_server/datadir
      - ~/teamcity/logs:/opt/teamcity/logs
    networks:
      - teamcity-network
 
  teamcity-agent:
    image: teamcity-android-agent
    deploy:
        resources:
            limits:
                memory: 6G
    volumes:
      - ~/teamcity/agent-conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=teamcity-server:8111
    networks:
      - teamcity-network
 
networks:
  teamcity-network:
